Riddler Classic
After a long night of frivolous quackery, two delirious ducks are having a difficult time finding each other in their pond. The pond happens to contain a 3×3 grid of rocks.

Every minute, each duck randomly swims, independently of the other duck, from one rock to a neighboring rock in the 3×3 grid — up, down, left or right, but not diagonally. So if a duck is at the middle rock, it will next swim to one of the four side rocks with probability 1/4. From a side rock, it will swim to one of the two adjacent corner rocks or back to the middle rock, each with probability 1/3. And from a corner rock, it will swim to one of the two adjacent side rocks with probability 1/2.

If the ducks both start at the middle rock, then on average, how long will it take until they’re at the same rock again? (Of course, there’s a 1/4 chance that they’ll swim in the same direction after the first minute, in which case it would only take one minute for them to be at the same rock again. But it could take much longer, if they happen to keep missing each other.)

Extra credit: What if there are three or more ducks? If they all start in the middle rock, on average, how long will it take until they are all at the same rock again?

Given that they both start on the center rock, there are five states that the two ducks can find themselves in:

- A: Adjacent Corners
- B: Opposite Edges
- C: Opposite Corners
- D: Center and Corner
- E: Adjacent Edges
- XYZ: Same Rock

In [12]:
import numpy as np
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [13]:
move = {'Start':'A', # It turns out that being in the start position is the same as being in the 'A' position
        'A':lambda: np.random.choice(['Y', 'B', 'E'], p=[1/4, 1/4, 2/4]), 
        'B':lambda: np.random.choice(['Z', 'A', 'C', 'D'], p=[1/9, 2/9, 2/9, 4/9]),
        'C':lambda: np.random.choice(['B', 'E'], p=[2/4, 2/4]),
        'D':lambda: np.random.choice(['Y','B', 'E'], p=[2/8, 2/8, 4/8]),
        'E':lambda: np.random.choice(['X', 'Z', 'A', 'C', 'D'], p=[1/9, 1/9, 2/9, 1/9, 4/9])
        }
# It turns out that being in the start position is the same as being in the 'A' position

In [15]:
count = 10000
run = 0
total_time=[]
while run<count:
    minutes=0
    position='A'
    while position not in ['X', 'Y', 'Z']:
        position=move.get(position)()
        minutes+=1
    total_time.append(minutes)
    run+=1
np.sum(total_time)/count
    

4.8457

In [16]:
363/74

4.905405405405405

In [17]:
elements, counts = np.unique(total_time,return_counts=True)
elements, counts

(array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 42,
        43]),
 array([2546, 1377, 1275, 839, 788, 591, 576, 371, 346, 222, 219, 161, 141,
        97, 85, 70, 68, 45, 32, 22, 26, 17, 19, 7, 14, 13, 8, 4, 4, 6, 1,
        5, 1, 1, 1, 1, 1]))

In [19]:
Q = np.array([[0, 1/4, 0, 0, 2/4],
              [2/9, 0, 2/9, 4/9, 0],
              [0, 1/2, 0, 0, 1/2],
              [0, 1/4, 0, 0, 1/2],
              [2/9, 0, 1/9, 4/9, 0]])

In [20]:
Q

array([[0, 1/4, 0, 0, 1/2],
       [2/9, 0, 2/9, 4/9, 0],
       [0, 1/2, 0, 0, 1/2],
       [0, 1/4, 0, 0, 1/2],
       [2/9, 0, 1/9, 4/9, 0]])

In [21]:
I = np.identity(5)

In [22]:
N = np.linalg.inv((I-Q))

In [23]:
N

array([[164/111, 57/74, 12/37, 106/111, 51/37],
       [76/111, 66/37, 20/37, 152/111, 48/37],
       [24/37, 45/37, 54/37, 48/37, 63/37],
       [53/111, 57/74, 12/37, 217/111, 51/37],
       [68/111, 24/37, 14/37, 136/111, 78/37]])

In [24]:
Ones = np.ones((5,1))

In [25]:
ans = N@Ones
ans

array([[363/74],
       [210/37],
       [234/37],
       [363/74],
       [184/37]])